### PR TITLE
Add http status to data field

### PR DESCRIPTION
**Pull request by kdumontnu**
I'm working on an implementation where it would be very helpful to have the status code of the request response. I think others might find this useful too.

### CODE REVIEW

**Comment by shrpne** [comment]
Maybe it will be more useful to save the whole request object then?

**Comment by kdumontnu** [comment]
> Maybe it will be more useful to save the whole request object then?

Either is fine with me. If you think it's cleaner to save the request object I'm happy to make the change (also don't mind if you want to change it). 

Thanks for the library btw.

**Comment by kdumontnu** [comment]
@shrpne any preference here? Status code is all I need. Might be simplest to just save the status as I have it here.

**Comment by shrpne** [comment]
Can you please update to save the whole request object and I will be glad to merge it

**Comment by shrpne** [comment]
completed in #60

**Pull request closed without merging**
